import type { Metadata } from "next";
import "./globals.css";
import { PoppinsFont } from "@/utils/font";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import StoreProvider from "./_providers/StoreProvider";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light" className={`${PoppinsFont.variable} `}>
      <StoreProvider>
        <AuthProvider>
          <body suppressHydrationWarning>
            <ToastContainer
              limit={3}
              autoClose={3500}
              draggablePercent={60}
              draggable
            />

            <Toaster />

            <main className="font-poppins">{children}</main>
          </body>
        </AuthProvider>
      </StoreProvider>
    </html>
  );
}